```yaml
# SPDX-License-Identifier: GPL-3.0-only
# Проверка соответствия лицензии GPL-3.0-only

name: License Compliance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  license-check:
    name: Enforce GPL-3.0-only
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check LICENSE file
        run: |
          if [ ! -f "LICENSE" ]; then
            echo "❌ Файл LICENSE отсутствует"
            exit 1
          fi
          if ! grep -q "GNU GENERAL PUBLIC LICENSE" LICENSE; then
            echo "❌ LICENSE не содержит текст GPL"
            exit 1
          fi
          echo "✅ LICENSE присутствует и содержит GPL"

      - name: Check GPL headers in source files
        run: |
          # Проверяем все .rs, .py, .sh, .yaml файлы на наличие SPDX-Identifier
          MISSING_HEADERS=0
          for file in $(find . -path ./.git -prune -o \
                                -path ./target -prune -o \
                                -path ./profiles -prune -o \
                                \( -name "*.rs" -o -name "*.py" -o -name "*.sh" -o -name "*.yaml" \) \
                                -print); do
            if ! grep -q "SPDX-License-Identifier: GPL-3.0-only" "$file"; then
              echo "⚠️  Отсутствует лицензионный заголовок в: $file"
              MISSING_HEADERS=$((MISSING_HEADERS + 1))
            fi
          done
          if [ $MISSING_HEADERS -gt 0 ]; then
            echo "❌ Найдено $MISSING_HEADERS файлов без лицензионного заголовка"
            exit 1
          else
            echo "✅ Все исходные файлы содержат SPDX-Identifier: GPL-3.0-only"
          fi

      - name: Check Cargo.toml license
        run: |
          if ! grep -q 'license = "GPL-3.0-only"' Cargo.toml; then
            echo "❌ Cargo.toml не указывает GPL-3.0-only"
            exit 1
          fi
          echo "✅ Cargo.toml корректно лицензирован"

      - name: Check pyproject.toml license
        run: |
          if ! grep -q "GPL-3.0-only" pyproject.toml; then
            echo "❌ pyproject.toml не содержит GPL-3.0-only"
            exit 1
          fi
          echo "✅ pyproject.toml корректно лицензирован"
```
